
from pydantic import BaseModel, Field


class InteractionState(BaseModel):
    """Shape of the 'Interaction Details' form on the left of the screen.
    The frontend renders directly from this object. The AI agent is the
    only thing that produces or mutates it.
    """

    id: str | None = Field(
        None,
        description="The unique UUID string identifying the interaction record.",
        examples=["4a1b6c78-90ab-cdef-1234-567890abcdef"],
    )
    hcp_name: str | None = Field(
        "",
        description="Name of the Healthcare Professional.",
        examples=["Dr. Sharma"],
    )
    interaction_type: str | None = Field(
        "Meeting",
        description="Type of contact (e.g. Meeting, Call, Email, Conference).",
        examples=["Meeting"],
    )
    date: str | None = Field(
        "",
        description="ISO format date string (YYYY-MM-DD).",
        examples=["2026-07-27"],
    )
    time: str | None = Field(
        "",
        description="Time of interaction in 24-hour format (HH:MM).",
        examples=["14:30"],
    )
    attendees: str | None = Field(
        "",
        description="Comma-separated list of attendees.",
        examples=["Dr. Sharma, Dr. Rao"],
    )
    topics_discussed: str | None = Field(
        "",
        description="Bullet points or summary of the topics discussed.",
        examples=["Discussed OncoBoost Phase III trial efficacy and patient recruitment criteria."],
    )
    materials_shared: list[str] = Field(
        default=[],
        description="Catalog or free-text names of marketing/educational materials shared.",
        examples=[["OncoBoost Phase III Brochure"]],
    )
    samples_distributed: list[str] = Field(
        default=[],
        description="Catalog or free-text names of drug samples distributed.",
        examples=[["OncoBoost 50mg Sample Pack"]],
    )
    sentiment: str | None = Field(
        "Neutral",
        description="Inferred sentiment of the HCP regarding the topics (Positive, Neutral, Negative).",
        examples=["Positive"],
    )
    outcomes: str | None = Field(
        "",
        description="Core outcomes or agreements reached during the interaction.",
        examples=["HCP agreed to review the clinical trial brochure and consider enrolling patients."],
    )
    follow_up_actions: str | None = Field(
        "",
        description="Specific follow-up actions planned for the sales representative.",
        examples=["Send the additional clinical safety profile data next week."],
    )
    ai_suggested_followups: list[str] = Field(
        default=[],
        description="Suggested follow-up tasks generated by the AI agent.",
        examples=[["Schedule follow-up meeting in 2 weeks", "Share safety documentation"]],
    )

    class Config:
        from_attributes = True


class ChatMessageIn(BaseModel):
    message: str = Field(
        ...,
        min_length=1,
        description="The natural language note or command sent by the field rep.",
        examples=["Met Dr. Sharma, discussed OncoBoost, positive sentiment, shared a brochure"],
    )
    current_state: InteractionState = Field(
        default_factory=InteractionState,
        description="The current state of the interaction details form in the UI, used as context.",
    )
    thread_id: str | None = Field(
        "default-session",
        description="Unique thread identifier to persist chat history and context across turns.",
        examples=["session_user_123"],
    )


class ChatMessageOut(BaseModel):
    reply: str = Field(
        ...,
        description="The AI agent's conversational response or execution summary.",
        examples=["Logged interaction with Dr. Sharma on 2026-07-27."],
    )
    tool_calls: list[str] = Field(
        default=[],
        description="The list of tools that were executed in this turn.",
        examples=[["log_interaction", "search_and_add_catalog_item"]],
    )
    updated_state: InteractionState = Field(
        ...,
        description="The updated state of the interaction details form after tool execution.",
    )
